/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { MenuItem } from "./types";

export const initialMenuItems: MenuItem[] = [
  // --- Soups ---
  { id: "soup-1", name: "Veg Hot & Sour", price: 120, category: "Soups", isVeg: true },
  { id: "soup-2", name: "Veg Mancho", price: 120, category: "Soups", isVeg: true },
  { id: "soup-3", name: "Veg Lemon & Coriander", price: 120, category: "Soups", isVeg: true },
  { id: "soup-4", name: "Chicken Mancho", price: 140, category: "Soups", isVeg: false },
  { id: "soup-5", name: "Chicken Hot & Sour", price: 140, category: "Soups", isVeg: false },
  { id: "soup-6", name: "Chicken Lemon & Coriander", price: 140, category: "Soups", isVeg: false },

  // --- Veg Starters ---
  { id: "vs-1", name: "Panneer Majestic", price: 240, category: "Veg Starters", isVeg: true },
  { id: "vs-2", name: "Crispy Corn", price: 210, category: "Veg Starters", isVeg: true },
  { id: "vs-3", name: "Paneer 65/Manchuria/Chilly", price: 240, category: "Veg Starters", isVeg: true },
  { id: "vs-4", name: "Mushroom 65/Manchuria/Chilly", price: 220, category: "Veg Starters", isVeg: true },
  { id: "vs-5", name: "Baby Corn 65/Manchuria/Chilly", price: 210, category: "Veg Starters", isVeg: true },

  // --- Non Veg Starters ---
  { id: "nvs-1", name: "Honey Chicken", price: 240, category: "Non Veg Starters", isVeg: false },
  { id: "nvs-2", name: "Chicken Mongolian", price: 240, category: "Non Veg Starters", isVeg: false },
  { id: "nvs-3", name: "Chicken RR", price: 240, category: "Non Veg Starters", isVeg: false },
  { id: "nvs-4", name: "Schezwan Chicken", price: 240, category: "Non Veg Starters", isVeg: false },
  { id: "nvs-5", name: "Dragon Chicken", price: 240, category: "Non Veg Starters", isVeg: false },
  { id: "nvs-6", name: "Chicken Majestic", price: 240, category: "Non Veg Starters", isVeg: false },
  { id: "nvs-7", name: "Chicken 555", price: 240, category: "Non Veg Starters", isVeg: false },
  { id: "nvs-8", name: "Chicken 65/Manchuria/Chilly", price: 240, category: "Non Veg Starters", isVeg: false },
  { id: "nvs-9", name: "Chicken Lollypops(4)", price: 200, category: "Non Veg Starters", isVeg: false },
  { id: "nvs-10", name: "Chicken Drumsticks(4)", price: 200, category: "Non Veg Starters", isVeg: false },
  { id: "nvs-11", name: "Garlic Chicken", price: 240, category: "Non Veg Starters", isVeg: false },
  { id: "nvs-12", name: "Chilly Fish", price: 220, category: "Non Veg Starters", isVeg: false },
  { id: "nvs-13", name: "Apollo Fish", price: 240, category: "Non Veg Starters", isVeg: false },
  { id: "nvs-14", name: "Loose Prawn", price: 280, category: "Non Veg Starters", isVeg: false },
  { id: "nvs-15", name: "Chilly Prawn", price: 280, category: "Non Veg Starters", isVeg: false },
  { id: "nvs-16", name: "Prawn 65", price: 280, category: "Non Veg Starters", isVeg: false },
  { id: "nvs-17", name: "Egg Chilly/Manchuria", price: 180, category: "Non Veg Starters", isVeg: false },

  // --- Non Veg Biryani ---
  { id: "nvb-1", name: "Chicken Fry Biryani.", price: 260, category: "Non Veg Biryani", isVeg: false },
  { id: "nvb-2", name: "Chicken Dum Biryani", price: 260, category: "Non Veg Biryani", isVeg: false },
  { id: "nvb-3", name: "Chicken Joint Biryani", price: 280, category: "Non Veg Biryani", isVeg: false },
  { id: "nvb-4", name: "Chicken Double Joint Biryani", price: 360, category: "Non Veg Biryani", isVeg: false },
  { id: "nvb-5", name: "Chicken Lollypop Biryani", price: 300, category: "Non Veg Biryani", isVeg: false },
  { id: "nvb-6", name: "Chicken Mughlai Biryani", price: 300, category: "Non Veg Biryani", isVeg: false },
  { id: "nvb-7", name: "Potlam Biryani", price: 380, category: "Non Veg Biryani", isVeg: false },
  { id: "nvb-8", name: "Chicken 65 Biryani", price: 300, category: "Non Veg Biryani", isVeg: false },
  { id: "nvb-9", name: "Chilly Chicken Biryani", price: 300, category: "Non Veg Biryani", isVeg: false },
  { id: "nvb-10", name: "Non Veg Mixed Biryani", price: 440, category: "Non Veg Biryani", isVeg: false },
  { id: "nvb-11", name: "Mutton Fry Biryani", price: 450, category: "Non Veg Biryani", isVeg: false },
  { id: "nvb-12", name: "Prawn Biryani", price: 300, category: "Non Veg Biryani", isVeg: false },
  { id: "nvb-13", name: "Fish Boneless Biryani", price: 300, category: "Non Veg Biryani", isVeg: false },
  { id: "nvb-14", name: "Chicken Special Boneless Biryani", price: 300, category: "Non Veg Biryani", isVeg: false },

  // --- Veg Biryani ---
  { id: "vb-1", name: "Veg Biryani", price: 180, category: "Veg Biryani", isVeg: true },
  { id: "vb-2", name: "Kaju Biryani", price: 240, category: "Veg Biryani", isVeg: true },
  { id: "vb-3", name: "Paneer Biryani", price: 240, category: "Veg Biryani", isVeg: true },
  { id: "vb-4", name: "Mushroom Biryani", price: 220, category: "Veg Biryani", isVeg: true },
  { id: "vb-5", name: "Kaju Paneer Biryani", price: 280, category: "Veg Biryani", isVeg: true },
  { id: "vb-6", name: "Biryani Rice", price: 140, category: "Veg Biryani", isVeg: true },
  { id: "vb-7", name: "Veg Meals", price: 150, category: "Veg Biryani", isVeg: true },

  // --- Veg Fried Rice ---
  { id: "vfr-1", name: "Veg Fried Rice", price: 160, category: "Veg Fried Rice", isVeg: true },
  { id: "vfr-2", name: "Kaju Fried Rice", price: 200, category: "Veg Fried Rice", isVeg: true },
  { id: "vfr-3", name: "Paneer Fried Rice", price: 220, category: "Veg Fried Rice", isVeg: true },
  { id: "vfr-4", name: "Mushroom Fried Rice", price: 200, category: "Veg Fried Rice", isVeg: true },
  { id: "vfr-5", name: "Baby Corn Fried Rice", price: 200, category: "Veg Fried Rice", isVeg: true },
  { id: "vfr-6", name: "Veg Schezwan Fried Rice", price: 200, category: "Veg Fried Rice", isVeg: true },
  { id: "vfr-7", name: "Veg Mixed Fried Rice", price: 240, category: "Veg Fried Rice", isVeg: true },

  // --- Non Veg Fried Rice ---
  { id: "nvfr-1", name: "Chicken Fried Rice", price: 220, category: "Non Veg Fried Rice", isVeg: false },
  { id: "nvfr-2", name: "Chicken Sezwan Fried Rice", price: 240, category: "Non Veg Fried Rice", isVeg: false },
  { id: "nvfr-3", name: "Special Chicken Fried Rice", price: 300, category: "Non Veg Fried Rice", isVeg: false },
  { id: "nvfr-4", name: "Egg Fried Rice", price: 180, category: "Non Veg Fried Rice", isVeg: false },
  { id: "nvfr-5", name: "Mutton Fried Rice", price: 340, category: "Non Veg Fried Rice", isVeg: false },
  { id: "nvfr-6", name: "Prawn Fried Rice", price: 300, category: "Non Veg Fried Rice", isVeg: false },
  { id: "nvfr-7", name: "Mixed Fried Rice", price: 320, category: "Non Veg Fried Rice", isVeg: false },

  // --- Veg Curries ---
  { id: "vc-1", name: "Mixed / Kadai Veg", price: 190, category: "Veg Curries", isVeg: true },
  { id: "vc-2", name: "Kaju Tomato Curry", price: 220, category: "Veg Curries", isVeg: true },
  { id: "vc-3", name: "Kaju Paneer Curry", price: 220, category: "Veg Curries", isVeg: true },
  { id: "vc-4", name: "Methi Chaman Curry", price: 220, category: "Veg Curries", isVeg: true },
  { id: "vc-5", name: "Paneer Butter Masala", price: 230, category: "Veg Curries", isVeg: true },
  { id: "vc-6", name: "Mutter Paneer", price: 240, category: "Veg Curries", isVeg: true },
  { id: "vc-7", name: "Paneer Kholapu", price: 260, category: "Veg Curries", isVeg: true },
  { id: "vc-8", name: "Mushroom Curry", price: 220, category: "Veg Curries", isVeg: true },

  // --- Non Veg Curries ---
  { id: "nvc-1", name: "Chicken Curry/Fry", price: 200, category: "Non Veg Curries", isVeg: false },
  { id: "nvc-2", name: "Chicken Boneless Curry", price: 260, category: "Non Veg Curries", isVeg: false },
  { id: "nvc-3", name: "Kadai Chicken Curry", price: 250, category: "Non Veg Curries", isVeg: false },
  { id: "nvc-4", name: "Chicken Mughlai Curry", price: 260, category: "Non Veg Curries", isVeg: false },
  { id: "nvc-5", name: "Mutton Curry", price: 400, category: "Non Veg Curries", isVeg: false },
  { id: "nvc-6", name: "Prawns Curry", price: 280, category: "Non Veg Curries", isVeg: false },
  { id: "nvc-7", name: "Egg Burji", price: 100, category: "Non Veg Curries", isVeg: false },

  // --- Others ---
  { id: "oth-1", name: "Chapathi/Parota Chicken", price: 180, category: "Others", isVeg: false },
  { id: "oth-2", name: "Chapathi/Parota Mutton", price: 400, category: "Others", isVeg: false },
  { id: "oth-3", name: "Pulka.", price: 20, category: "Others", isVeg: true },
  { id: "oth-4", name: "Butter Pulka", price: 30, category: "Others", isVeg: true },
  { id: "oth-5", name: "Double Egg Omelette", price: 80, category: "Others", isVeg: false },
  { id: "oth-6", name: "Double Egg Masala Omelette", price: 120, category: "Others", isVeg: false },
  { id: "oth-7", name: "Water Bottle", price: 20, category: "Others", isVeg: true },
  { id: "oth-8", name: "Soft Drink", price: 20, category: "Others", isVeg: true },

  // --- Tiffins (Retained for system compatibility) ---
  { id: "tiff-1", name: "Idly (3pcs)", price: 50, category: "Tiffins", isVeg: true },
  { id: "tiff-2", name: "Sambar Idly (2)", price: 50, category: "Tiffins", isVeg: true },
  { id: "tiff-3", name: "Ghee Karam Idly (2)", price: 50, category: "Tiffins", isVeg: true },
  { id: "tiff-4", name: "Mysore Bonda (4)", price: 50, category: "Tiffins", isVeg: true },
  { id: "tiff-5", name: "Upma", price: 50, category: "Tiffins", isVeg: true },
  { id: "tiff-6", name: "Tomato Bath", price: 50, category: "Tiffins", isVeg: true },
  { id: "tiff-7", name: "Vada (3)", price: 50, category: "Tiffins", isVeg: true },
  { id: "tiff-8", name: "Sambar Vada (2)", price: 50, category: "Tiffins", isVeg: true },
  { id: "tiff-9", name: "Idly (2) + Vada Combo (2)", price: 50, category: "Tiffins", isVeg: true },
  { id: "tiff-10", name: "Curd Vada (2)", price: 60, category: "Tiffins", isVeg: true },
  { id: "tiff-11", name: "Plain Dosa", price: 50, category: "Tiffins", isVeg: true },
  { id: "tiff-12", name: "Masala Dosa", price: 60, category: "Tiffins", isVeg: true },
  { id: "tiff-13", name: "Upma Dosa", price: 60, category: "Tiffins", isVeg: true },
  { id: "tiff-14", name: "Onion Dosa", price: 60, category: "Tiffins", isVeg: true },
  { id: "tiff-15", name: "Ghee Masala Dosa", price: 70, category: "Tiffins", isVeg: true },
  { id: "tiff-16", name: "Ghee Onion Dosa", price: 70, category: "Tiffins", isVeg: true },
  { id: "tiff-17", name: "Plain Ravva Dosa", price: 55, category: "Tiffins", isVeg: true },
  { id: "tiff-18", name: "Onion Ravva Dosa", price: 70, category: "Tiffins", isVeg: true },
  { id: "tiff-19", name: "Ravva Masala Dosa", price: 70, category: "Tiffins", isVeg: true },
  { id: "tiff-20", name: "Ravva Onion Masala", price: 75, category: "Tiffins", isVeg: true },
  { id: "tiff-21", name: "70 MM M.L.A Dosa", price: 75, category: "Tiffins", isVeg: true },
  { id: "tiff-22", name: "70 MM Masala Dosa", price: 80, category: "Tiffins", isVeg: true },
  { id: "tiff-23", name: "Ghee Karam Dosa", price: 70, category: "Tiffins", isVeg: true },
  { id: "tiff-24", name: "Ghee Plain Dosa", price: 60, category: "Tiffins", isVeg: true },
  { id: "tiff-25", name: "Paneer Dosa", price: 100, category: "Tiffins", isVeg: true },
  { id: "tiff-26", name: "Plain Pesara", price: 40, category: "Tiffins", isVeg: true },
  { id: "tiff-27", name: "Onion Pesara", price: 50, category: "Tiffins", isVeg: true },
  { id: "tiff-28", name: "Upma Pesara", price: 40, category: "Tiffins", isVeg: true },
  { id: "tiff-29", name: "Plain Uthappam", price: 40, category: "Tiffins", isVeg: true },
  { id: "tiff-30", name: "Onion Uthappam", price: 40, category: "Tiffins", isVeg: true },
  { id: "tiff-31", name: "Chapathi", price: 40, category: "Tiffins", isVeg: true },
  { id: "tiff-32", name: "Single Chapathi", price: 35, category: "Tiffins", isVeg: true },
  { id: "tiff-33", name: "Parota", price: 40, category: "Tiffins", isVeg: true },
  { id: "tiff-34", name: "Single Parota", price: 35, category: "Tiffins", isVeg: true },
  { id: "tiff-35", name: "Poori", price: 40, category: "Tiffins", isVeg: true },
  { id: "tiff-36", name: "Single Poori", price: 35, category: "Tiffins", isVeg: true },
  { id: "tiff-37", name: "Meals", price: 60, category: "Tiffins", isVeg: true },
  { id: "tiff-38", name: "Executive Meals", price: 60, category: "Tiffins", isVeg: true },
  { id: "tiff-39", name: "Meals Parcel", price: 60, category: "Tiffins", isVeg: true },
  { id: "tiff-40", name: "Small Meals Parcel", price: 60, category: "Tiffins", isVeg: true },
  { id: "tiff-41", name: "Rice Pori", price: 50, category: "Tiffins", isVeg: true },
  { id: "tiff-42", name: "Pulihora", price: 70, category: "Tiffins", isVeg: true },
  { id: "tiff-43", name: "Veg Biryani (Breakfast)", price: 80, category: "Tiffins", isVeg: true },
  { id: "tiff-44", name: "Curd Rice", price: 50, category: "Tiffins", isVeg: true },
  { id: "tiff-45", name: "Veg Rice", price: 80, category: "Tiffins", isVeg: true },
  { id: "tiff-46", name: "Pappu", price: 30, category: "Tiffins", isVeg: true },
  { id: "tiff-47", name: "Veg Fry", price: 30, category: "Tiffins", isVeg: true },
  { id: "tiff-48", name: "Veg Curry", price: 30, category: "Tiffins", isVeg: true },
  { id: "tiff-49", name: "Sambar", price: 30, category: "Tiffins", isVeg: true },
  { id: "tiff-50", name: "Rasam", price: 20, category: "Tiffins", isVeg: true },
  { id: "tiff-51", name: "Roti Chutney", price: 20, category: "Tiffins", isVeg: true },
  { id: "tiff-52", name: "Majjiga Pulusu", price: 30, category: "Tiffins", isVeg: true },
  { id: "tiff-53", name: "Sponge Dosa (2)", price: 60, category: "Tiffins", isVeg: true },
  { id: "tiff-54", name: "Set Dosa (3)", price: 60, category: "Tiffins", isVeg: true },
  { id: "tiff-55", name: "Chitti Pesarattu (2)", price: 60, category: "Tiffins", isVeg: true },
  { id: "tiff-56", name: "Dibba Rotti", price: 60, category: "Tiffins", isVeg: true },
  { id: "tiff-57", name: "Poori (1) + Idly (2) Combo", price: 50, category: "Tiffins", isVeg: true },

  // --- Special Combos (Retained for system compatibility) ---
  { id: "sc-1", name: "Onion Bonda", price: 50, category: "Special Combos", isVeg: true },
  { id: "sc-2", name: "Poori + Vada Combo", price: 60, category: "Special Combos", isVeg: true },
  { id: "sc-3", name: "Ghee Karam Sponge", price: 80, category: "Special Combos", isVeg: true },
  { id: "sc-4", name: "Ghee Karam Pesara", price: 70, category: "Special Combos", isVeg: true },
  { id: "sc-5", name: "Onion Pesara Masala", price: 80, category: "Special Combos", isVeg: true },
  { id: "sc-6", name: "Idly + Bonda Combo", price: 50, category: "Special Combos", isVeg: true },
  { id: "sc-7", name: "Vada + Bonda Combo", price: 60, category: "Special Combos", isVeg: true },
  { id: "sc-8", name: "Bonda + Poori", price: 60, category: "Special Combos", isVeg: true },
  { id: "sc-9", name: "Idly + Upma", price: 50, category: "Special Combos", isVeg: true },
  { id: "sc-10", name: "Poori + Upma", price: 60, category: "Special Combos", isVeg: true },
  { id: "sc-11", name: "Vada + Upma", price: 50, category: "Special Combos", isVeg: true },
  { id: "sc-12", name: "Single Sambar Idly", price: 25, category: "Special Combos", isVeg: true },
  { id: "sc-13", name: "Single Sambar Vada", price: 30, category: "Special Combos", isVeg: true },
  { id: "sc-14", name: "Single Sponge", price: 35, category: "Special Combos", isVeg: true },
  { id: "sc-15", name: "Vada (2)", price: 35, category: "Special Combos", isVeg: true },
  { id: "sc-16", name: "Single Chitti Pesara", price: 35, category: "Special Combos", isVeg: true }
];
